name: "video-frame-extractor"
version: "1.0.0"
description: "Extract frames from video for AI analysis"
category: "media-processing"
author: "Custom Element"

inputs:
  - name: "video_file"
    type: "file"
    formats: ["mp4", "avi", "mov", "mkv", "webm"]
    required: true
    description: "Video file to extract frames from"
  
  - name: "frame_interval_seconds"
    type: "integer"
    default: 20
    min: 1
    max: 300
    description: "Interval between extracted frames in seconds"

outputs:
  - name: "frame_objects"
    type: "array"
    description: "Array of frame objects with timestamps and base64 images"
    
  - name: "video_info"
    type: "object"
    description: "Video metadata (fps, duration, dimensions)"

implementation:
  type: "python"
  entry_point: "video_frame_extractor_element.py"
  main_function: "webai_process_video"

dependencies:
  - opencv-python>=4.5.0
  - numpy>=1.21.0

tags:
  - video
  - frame-extraction
  - computer-vision
  - ai-analysis 